development:
  adapter: sqlite3
  encoding: utf8
  reconnect: false
  database: db/msdb_development.sqlite3
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
  timeout: 10000

test: &test
  adapter: sqlite3
  encoding: utf8
  reconnect: false
  database: db/msdb_test.sqlite3
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
  timeout: 10000


production:
  host: localhost
  encoding: utf8
  adapter: mysql2
  database:
  username:
  password:

cucumber:
  <<: *test

